### ISSUE TITLE
你这都需要集成Spider基类，然后重写parse，烦死了

### ISSUE THREAD

**Issue by ydf0509** [Ntrashh/traspider#1]
你这都需要集成Spider基类，然后重写parse，烦死了。

**Comment by 1mn0i** [comment]
可以加我微信交流交流



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月7日(星期六) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Ntrashh/traspider] 你这都需要集成Spider基类，然后重写parse，烦死了 (Issue #1)





 
你这都需要集成Spider基类，然后重写parse，烦死了。

**Comment by ydf0509** [comment]
什么微信号

**Comment by 1mn0i** [comment]
README里面有二维码





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月7日(星期六) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Ntrashh/traspider] 你这都需要集成Spider基类，然后重写parse，烦死了 (Issue #1)





 
什么微信号
